CREATE TYPE user_role AS ENUM (
    'admin',
    'cashier',
    'client',
    'dealer'
);

CREATE TYPE payment_type AS ENUM (
    'cash',
    'card',
    'transfer'
);

CREATE TYPE stock_action AS ENUM (
    'sale',
    'restock',
    'return'
);

CREATE TYPE sale_status AS ENUM (
    'pending',
    'received',
    'canceled'
);


-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE users (
                       id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                       username VARCHAR NOT NULL UNIQUE,
                       name VARCHAR NOT NULL,
                       data VARCHAR,
                       email VARCHAR,
                       phone_number VARCHAR[] NOT NULL DEFAULT ARRAY[]::VARCHAR[],
                       password_hash VARCHAR NOT NULL,
                       role user_role NOT NULL DEFAULT 'client',
                       created TIMESTAMP NOT NULL DEFAULT NOW(),
                       updated TIMESTAMP NOT NULL DEFAULT NOW()
);


-- ============================================================
-- MEASUREMENTS
-- ============================================================

CREATE TABLE measurements (
                              id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR NOT NULL,
                              unit_symbol VARCHAR NOT NULL UNIQUE,
                              created TIMESTAMP NOT NULL DEFAULT NOW(),
                              updated TIMESTAMP NOT NULL DEFAULT NOW()
);


-- ============================================================
-- CATEGORIES
-- ============================================================

CREATE TABLE categories (
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR NOT NULL,
                            measurement_id INT NOT NULL,
                            category_id INT,
                            created TIMESTAMP NOT NULL DEFAULT NOW(),
                            updated TIMESTAMP NOT NULL DEFAULT NOW(),

                            CONSTRAINT fk_categories_measurement
                                FOREIGN KEY (measurement_id)
                                    REFERENCES measurements(id),

                            CONSTRAINT fk_categories_parent
                                FOREIGN KEY (category_id)
                                    REFERENCES categories(id)
);


-- ============================================================
-- PRODUCTS
-- ============================================================

CREATE TABLE products (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR NOT NULL,
                          category_id INT NOT NULL,
                          created TIMESTAMP NOT NULL DEFAULT NOW(),
                          updated TIMESTAMP NOT NULL DEFAULT NOW(),

                          CONSTRAINT fk_products_category
                              FOREIGN KEY (category_id)
                                  REFERENCES categories(id)
);


-- ============================================================
-- PRODUCTS BALANCE
-- ============================================================

CREATE TABLE products_balance (
                                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  product_id INT NOT NULL UNIQUE,
                                  quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
                                  amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
                                  created TIMESTAMP NOT NULL DEFAULT NOW(),
                                  updated TIMESTAMP NOT NULL DEFAULT NOW(),

                                  CONSTRAINT fk_products_balance_product
                                      FOREIGN KEY (product_id)
                                          REFERENCES products(id),

                                  CONSTRAINT chk_products_balance_quantity
                                      CHECK (quantity >= 0),

                                  CONSTRAINT chk_products_balance_amount
                                      CHECK (amount >= 0)
);


-- ============================================================
-- STOCK MOVEMENTS
-- ============================================================

CREATE TABLE stock_movements (
                                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 product_id INT NOT NULL,
                                 movement_type stock_action NOT NULL,
                                 quantity NUMERIC(12, 3) NOT NULL,
                                 unit_price NUMERIC(12, 2) NOT NULL,

                                 total_amount NUMERIC(12, 2)
                                     GENERATED ALWAYS AS (quantity * unit_price) STORED,

                                 created TIMESTAMP NOT NULL DEFAULT NOW(),

                                 CONSTRAINT fk_stock_movements_product
                                     FOREIGN KEY (product_id)
                                         REFERENCES products(id),

                                 CONSTRAINT chk_stock_movements_quantity
                                     CHECK (quantity > 0),

                                 CONSTRAINT chk_stock_movements_price
                                     CHECK (unit_price >= 0)
);


-- ============================================================
-- SALES
-- ============================================================

CREATE TABLE sales (
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       cashier_id UUID NOT NULL,
                       client_id UUID,
                       total_amount NUMERIC(12, 2) NOT NULL,
                       status sale_status NOT NULL DEFAULT 'pending',
                       created TIMESTAMP NOT NULL DEFAULT NOW(),

                       CONSTRAINT fk_sales_cashier
                           FOREIGN KEY (cashier_id)
                               REFERENCES users(id),

                       CONSTRAINT fk_sales_client
                           FOREIGN KEY (client_id)
                               REFERENCES users(id),

                       CONSTRAINT chk_sales_total
                           CHECK (total_amount >= 0)
);


-- ============================================================
-- SALE ITEMS
-- ============================================================

CREATE TABLE sale_items (
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            sale_id INT NOT NULL,
                            product_id INT NOT NULL,
                            quantity NUMERIC(12, 3) NOT NULL,
                            price NUMERIC(12, 2) NOT NULL,

                            CONSTRAINT fk_sale_items_sale
                                FOREIGN KEY (sale_id)
                                    REFERENCES sales(id)
                                    ON DELETE CASCADE,

                            CONSTRAINT fk_sale_items_product
                                FOREIGN KEY (product_id)
                                    REFERENCES products(id),

                            CONSTRAINT chk_sale_items_quantity
                                CHECK (quantity > 0),

                            CONSTRAINT chk_sale_items_price
                                CHECK (price >= 0)
);


-- ============================================================
-- PAYMENTS
-- ============================================================

CREATE TABLE payments (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          sale_id INT NOT NULL,
                          amount NUMERIC(12, 2) NOT NULL,
                          type payment_type NOT NULL,
                          created TIMESTAMP NOT NULL DEFAULT NOW(),

                          CONSTRAINT fk_payments_sale
                              FOREIGN KEY (sale_id)
                                  REFERENCES sales(id)
                                  ON DELETE CASCADE,

                          CONSTRAINT chk_payments_amount
                              CHECK (amount > 0)
);


-- ============================================================
-- PURCHASE ORDERS
-- ============================================================

CREATE TABLE purchase_orders (
                                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 dealer_id UUID,
                                 created TIMESTAMP NOT NULL DEFAULT NOW(),

                                 CONSTRAINT fk_purchase_orders_dealer
                                     FOREIGN KEY (dealer_id)
                                         REFERENCES users(id)
);


-- ============================================================
-- PURCHASE ITEMS
-- ============================================================

CREATE TABLE purchase_items (
                                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                purchase_order_id INT NOT NULL,
                                product_id INT NOT NULL,
                                quantity NUMERIC(12, 3) NOT NULL,
                                price NUMERIC(12, 2) NOT NULL,
                                status BOOLEAN NOT NULL DEFAULT FALSE,

                                CONSTRAINT fk_purchase_items_order
                                    FOREIGN KEY (purchase_order_id)
                                        REFERENCES purchase_orders(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT fk_purchase_items_product
                                    FOREIGN KEY (product_id)
                                        REFERENCES products(id),

                                CONSTRAINT chk_purchase_items_quantity
                                    CHECK (quantity > 0),

                                CONSTRAINT chk_purchase_items_price
                                    CHECK (price >= 0)
);


-- ============================================================
-- PURCHASE EXPENSES
-- ============================================================

CREATE TABLE purchase_expenses (
                                   id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   purchase_item_id INT NOT NULL,
                                   data VARCHAR,
                                   amount NUMERIC(12, 2) NOT NULL,
                                   created TIMESTAMP NOT NULL DEFAULT NOW(),
                                   updated TIMESTAMP NOT NULL DEFAULT NOW(),

                                   CONSTRAINT fk_purchase_expenses_item
                                       FOREIGN KEY (purchase_item_id)
                                           REFERENCES purchase_items(id)
                                           ON DELETE CASCADE,

                                   CONSTRAINT chk_purchase_expenses_amount
                                       CHECK (amount >= 0)
);


-- ============================================================
-- ASSETS
-- ============================================================

CREATE TABLE assets (
                        id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                        sale_id INT,
                        created TIMESTAMP NOT NULL DEFAULT NOW(),

                        CONSTRAINT fk_assets_sale
                            FOREIGN KEY (sale_id)
                                REFERENCES sales(id)
                                ON DELETE SET NULL
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_products_category
    ON products(category_id);

CREATE INDEX idx_stock_movements_product
    ON stock_movements(product_id);

CREATE INDEX idx_stock_movements_created
    ON stock_movements(created);

CREATE INDEX idx_sales_cashier
    ON sales(cashier_id);

CREATE INDEX idx_sales_client
    ON sales(client_id);

CREATE INDEX idx_sale_items_sale
    ON sale_items(sale_id);

CREATE INDEX idx_sale_items_product
    ON sale_items(product_id);

CREATE INDEX idx_purchase_items_order
    ON purchase_items(purchase_order_id);

CREATE INDEX idx_purchase_items_product
    ON purchase_items(product_id);

CREATE INDEX idx_purchase_expenses_item
    ON purchase_expenses(purchase_item_id);


-- ============================================================
-- PURCHASE / RESTOCK FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION inp_product()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN

INSERT INTO stock_movements (
    product_id,
    movement_type,
    quantity,
    unit_price
)
VALUES (
           NEW.product_id,
           'restock',
           NEW.quantity,
           NEW.price
       );

INSERT INTO products_balance (
    product_id,
    quantity,
    amount
)
VALUES (
           NEW.product_id,
           NEW.quantity,
           NEW.price
       )
    ON CONFLICT (product_id)
    DO UPDATE SET
    quantity = products_balance.quantity + EXCLUDED.quantity,
               amount = products_balance.amount + EXCLUDED.amount,
               updated = CURRENT_TIMESTAMP;

RETURN NEW;
END;
$$;


-- ============================================================
-- SALE / STOCK OUT FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION out_product()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
current_quantity NUMERIC(12, 3);
    current_amount NUMERIC(12, 2);
    cost_per_unit NUMERIC(12, 6);
    stock_cost NUMERIC(12, 2);
BEGIN

SELECT
    quantity,
    amount
INTO
    current_quantity,
    current_amount
FROM products_balance
WHERE product_id = NEW.product_id
    FOR UPDATE;

IF current_quantity IS NULL THEN
        RAISE EXCEPTION
            'Product % has no stock balance',
            NEW.product_id;
END IF;

    IF current_quantity < NEW.quantity THEN
        RAISE EXCEPTION
            'Insufficient stock for product %. Current quantity: %, requested: %',
            NEW.product_id,
            current_quantity,
            NEW.quantity;
END IF;

    IF current_quantity > 0 THEN
        cost_per_unit := current_amount / current_quantity;
ELSE
        cost_per_unit := 0;
END IF;

    stock_cost := ROUND(
        NEW.quantity * cost_per_unit,
        2
    );

INSERT INTO stock_movements (
    product_id,
    movement_type,
    quantity,
    unit_price
)
VALUES (
           NEW.product_id,
           'sale',
           NEW.quantity,
           NEW.price
       );

UPDATE products_balance
SET
    quantity = quantity - NEW.quantity,
    amount = GREATEST(amount - stock_cost, 0),
    updated = CURRENT_TIMESTAMP
WHERE product_id = NEW.product_id;

RETURN NEW;
END;
$$;


-- ============================================================
-- PURCHASE EXPENSE FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION expenses_product()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
product_id_value INT;
BEGIN

SELECT product_id
INTO product_id_value
FROM purchase_items
WHERE id = NEW.purchase_item_id;

IF product_id_value IS NULL THEN
        RAISE EXCEPTION
            'Purchase item % does not exist',
            NEW.purchase_item_id;
END IF;

INSERT INTO products_balance (
    product_id,
    quantity,
    amount
)
VALUES (
           product_id_value,
           0,
           NEW.amount
       )
    ON CONFLICT (product_id)
    DO UPDATE SET
    amount = products_balance.amount + EXCLUDED.amount,
               updated = CURRENT_TIMESTAMP;

RETURN NEW;
END;
$$;


-- ============================================================
-- TRIGGERS
-- ============================================================

CREATE TRIGGER trg_purchase_item_stock_in
    AFTER INSERT ON purchase_items
    FOR EACH ROW
    EXECUTE FUNCTION inp_product();


CREATE TRIGGER trg_sale_item_stock_out
    AFTER INSERT ON sale_items
    FOR EACH ROW
    EXECUTE FUNCTION out_product();


CREATE TRIGGER trg_purchase_expense_balance
    AFTER INSERT ON purchase_expenses
    FOR EACH ROW
    EXECUTE FUNCTION expenses_product();


-- ============================================================
-- DEFAULT MEASUREMENTS
-- ============================================================

INSERT INTO measurements (name, unit_symbol)
VALUES
    ('Weight', 'kg'),
    ('Length', 'm'),
    ('Volume', 'L'),
    ('Pieces', 'pcs');