CREATE TYPE "user_role" AS ENUM (
  'admin',
  'cashier',
  'client',
  'dealer'
);

CREATE TYPE "payment_type" AS ENUM (
  'cash',
  'card',
  'transfer'
);

CREATE TYPE "stock_action" AS ENUM (
  'sale',
  'restock',
  'return'
);

CREATE TYPE "sale_status" AS ENUM (
  'pending',
  'received',
  'canceled'
);

CREATE TABLE "users"
(
    "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"          varchar,
    "email"         varchar UNIQUE,
    "phone_number"  varchar UNIQUE,
    "password_hash" varchar,
    "role"          user_role,
    "created"       timestamp DEFAULT (now()),
    "updated"       timestamp DEFAULT (now())
);

CREATE TABLE "categories"
(
    "id"      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"    varchar,
    "created" timestamp DEFAULT (now())
);

CREATE TABLE "products"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        varchar,
    "category_id" int,
    "dealer_id"   int,
    "price"       decimal,
    "stock"       int,
    "created"     timestamp DEFAULT (now()),
    "updated"     timestamp DEFAULT (now())
);

CREATE TABLE "sales"
(
    "id"           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cashier_id"   int,
    "client_id"    int,
    "total_amount" decimal,
    "status"       sale_status,
    "created"      timestamp DEFAULT (now())
);

CREATE TABLE "sale_items"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sale_id"    int,
    "product_id" int,
    "quantity"   int,
    "price"      decimal
);

CREATE TABLE "payments"
(
    "id"      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sale_id" int,
    "amount"  decimal,
    "type"    payment_type,
    "created" timestamp DEFAULT (now())
);

CREATE TABLE "stock_movements"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_id" int,
    "quantity"   int,
    "action"     stock_action,
    "created"    timestamp DEFAULT (now())
);

CREATE TABLE "purchase_orders"
(
    "id"           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dealer_id"    int,
    "total_amount" decimal,
    "status"       varchar,
    "created"      timestamp DEFAULT (now())
);

CREATE TABLE "purchase_items"
(
    "id"                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "purchase_order_id" int,
    "product_id"        int,
    "quantity"          int,
    "price"             decimal,
    "total"             decimal
);

CREATE TABLE "assets"
(
    "id"      UUID      DEFAULT gen_random_uuid() PRIMARY KEY,
    "sale_id" int,
    "created" timestamp DEFAULT (now())
);

ALTER TABLE "assets"
    ADD FOREIGN KEY ("sale_id") REFERENCES "sales" ("id");

ALTER TABLE "products"
    ADD FOREIGN KEY ("dealer_id") REFERENCES "users" ("id");

ALTER TABLE "purchase_orders"
    ADD FOREIGN KEY ("dealer_id") REFERENCES "users" ("id");

ALTER TABLE "purchase_items"
    ADD FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders" ("id");

ALTER TABLE "purchase_items"
    ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "products"
    ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "sales"
    ADD FOREIGN KEY ("cashier_id") REFERENCES "users" ("id");

ALTER TABLE "sales"
    ADD FOREIGN KEY ("client_id") REFERENCES "users" ("id");

ALTER TABLE "sale_items"
    ADD FOREIGN KEY ("sale_id") REFERENCES "sales" ("id");

ALTER TABLE "sale_items"
    ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "payments"
    ADD FOREIGN KEY ("sale_id") REFERENCES "sales" ("id");

ALTER TABLE "stock_movements"
    ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");
