CREATE TYPE "user_role" AS ENUM (
  'admin',
  'cashier',
  'client',
  'dealer'
);

CREATE TYPE "payment_type" AS ENUM (
  'cash',
  'card',
  'transfer'
);

CREATE TYPE "stock_action" AS ENUM (
  'sale',
  'restock',
  'return'
);

CREATE TYPE "sale_status" AS ENUM (
  'pending',
  'received',
  'canceled'
);

CREATE TABLE "users"
(
    "id"            UUID      DEFAULT gen_random_uuid() PRIMARY KEY,
    "username"      varchar not null unique,
    "name"          varchar not null,
    "data"          varchar,
    "email"         varchar,
    "phone_number"  varchar[] NOT NULL DEFAULT ARRAY[]::varchar[],
    "password_hash" varchar not null,
    "role"          user_role DEFAULT 'client',
    "created"       timestamp DEFAULT (now()),
    "updated"       timestamp DEFAULT (now())
);

CREATE TABLE "categories"
(
    "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"           varchar NOT NULL,
    "measurement_id" int     NOT NULL,
    "created"        timestamp DEFAULT (now()),
    "updated"        timestamp DEFAULT (now())
);

CREATE TABLE "measurements"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        VARCHAR NOT NULL, -- e.g. Weight, Length, Volume
    "unit_symbol" VARCHAR NOT NULL, -- kg, m, L, pcs
    "created"     TIMESTAMP DEFAULT NOW(),
    "updated"     TIMESTAMP DEFAULT NOW()
);

CREATE TABLE "products"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        varchar not null,
    "category_id" int     not null,
    "created"     timestamp DEFAULT (now()),
    "updated"     timestamp DEFAULT (now())
);

CREATE TABLE "sales"
(
    "id"           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cashier_id"   UUID NOT NULL,
    "client_id"    UUID NOT NULL,
    "total_amount" decimal,
    "status"       sale_status DEFAULT 'pending',
    "created"      timestamp   DEFAULT (now())
);

CREATE TABLE "sale_items"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sale_id"    int NOT NULL,
    "product_id" int NOT NULL,
    "quantity"   int,
    "price"      decimal
);

CREATE TABLE "payments"
(
    "id"      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sale_id" int,
    "amount"  decimal,
    "type"    payment_type,
    "created" timestamp DEFAULT (now())
);

CREATE TABLE "stock_movements"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_id" int,
    "quantity"   int,
    "action"     stock_action,
    "created"    timestamp DEFAULT (now())
);

CREATE TABLE "purchase_orders"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dealer_id"   UUID,
    "created"     timestamp DEFAULT (now()),
    "consumption" decimal
);

CREATE TABLE "purchase_items"
(
    "id"                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "purchase_order_id" int     not null,
    "product_id"        int     not null,
    "quantity"          int     not null,
    "price"             decimal not null,
    "status"            bool    not null DEFAULT false
);

CREATE TABLE "assets"
(
    "id"      UUID      DEFAULT gen_random_uuid() PRIMARY KEY,
    "sale_id" int,
    "created" timestamp DEFAULT (now())
);

ALTER TABLE "assets"
    ADD FOREIGN KEY ("sale_id") REFERENCES "sales" ("id");

ALTER TABLE "purchase_orders"
    ADD FOREIGN KEY ("dealer_id") REFERENCES "users" ("id");

ALTER TABLE "purchase_items"
    ADD FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders" ("id");

ALTER TABLE "purchase_items"
    ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "products"
    ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "categories"
    ADD FOREIGN KEY ("measurement_id") REFERENCES "measurements" ("id");

ALTER TABLE "sales"
    ADD FOREIGN KEY ("cashier_id") REFERENCES "users" ("id");

ALTER TABLE "sales"
    ADD FOREIGN KEY ("client_id") REFERENCES "users" ("id");

ALTER TABLE "sale_items"
    ADD FOREIGN KEY ("sale_id") REFERENCES "sales" ("id");

ALTER TABLE "sale_items"
    ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "payments"
    ADD FOREIGN KEY ("sale_id") REFERENCES "sales" ("id");

ALTER TABLE "stock_movements"
    ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

INSERT INTO measurements (name, unit_symbol)
VALUES ('Weight', 'kg'),
       ('Length', 'm'),
       ('Volume', 'L'),
       ('Pieces', 'pcs');