// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentType string

const (
	PaymentTypeCash     PaymentType = "cash"
	PaymentTypeCard     PaymentType = "card"
	PaymentTypeTransfer PaymentType = "transfer"
)

func (e *PaymentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentType(s)
	case string:
		*e = PaymentType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentType: %T", src)
	}
	return nil
}

type NullPaymentType struct {
	PaymentType PaymentType `json:"payment_type"`
	Valid       bool        `json:"valid"` // Valid is true if PaymentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentType), nil
}

type SaleStatus string

const (
	SaleStatusPending  SaleStatus = "pending"
	SaleStatusReceived SaleStatus = "received"
	SaleStatusCanceled SaleStatus = "canceled"
)

func (e *SaleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SaleStatus(s)
	case string:
		*e = SaleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SaleStatus: %T", src)
	}
	return nil
}

type NullSaleStatus struct {
	SaleStatus SaleStatus `json:"sale_status"`
	Valid      bool       `json:"valid"` // Valid is true if SaleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSaleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SaleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SaleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSaleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SaleStatus), nil
}

type StockAction string

const (
	StockActionSale    StockAction = "sale"
	StockActionRestock StockAction = "restock"
	StockActionReturn  StockAction = "return"
)

func (e *StockAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockAction(s)
	case string:
		*e = StockAction(s)
	default:
		return fmt.Errorf("unsupported scan type for StockAction: %T", src)
	}
	return nil
}

type NullStockAction struct {
	StockAction StockAction `json:"stock_action"`
	Valid       bool        `json:"valid"` // Valid is true if StockAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockAction) Scan(value interface{}) error {
	if value == nil {
		ns.StockAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockAction), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleCashier UserRole = "cashier"
	UserRoleClient  UserRole = "client"
	UserRoleDealer  UserRole = "dealer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Asset struct {
	ID      pgtype.UUID      `json:"id"`
	SaleID  *int             `json:"sale_id"`
	Created pgtype.Timestamp `json:"created"`
}

type Category struct {
	ID      int              `json:"id"`
	Name    *string          `json:"name"`
	Created pgtype.Timestamp `json:"created"`
}

type Payment struct {
	ID      int              `json:"id"`
	SaleID  *int             `json:"sale_id"`
	Amount  pgtype.Numeric   `json:"amount"`
	Type    NullPaymentType  `json:"type"`
	Created pgtype.Timestamp `json:"created"`
}

type Product struct {
	ID         int              `json:"id"`
	Name       *string          `json:"name"`
	CategoryID *int             `json:"category_id"`
	DealerID   pgtype.UUID      `json:"dealer_id"`
	Price      pgtype.Numeric   `json:"price"`
	Stock      *int             `json:"stock"`
	Created    pgtype.Timestamp `json:"created"`
	Updated    pgtype.Timestamp `json:"updated"`
}

type PurchaseItem struct {
	ID              int            `json:"id"`
	PurchaseOrderID *int           `json:"purchase_order_id"`
	ProductID       *int           `json:"product_id"`
	Quantity        *int           `json:"quantity"`
	Price           pgtype.Numeric `json:"price"`
	Total           pgtype.Numeric `json:"total"`
}

type PurchaseOrder struct {
	ID          int              `json:"id"`
	DealerID    pgtype.UUID      `json:"dealer_id"`
	TotalAmount pgtype.Numeric   `json:"total_amount"`
	Status      *string          `json:"status"`
	Created     pgtype.Timestamp `json:"created"`
}

type Sale struct {
	ID          int              `json:"id"`
	CashierID   pgtype.UUID      `json:"cashier_id"`
	ClientID    pgtype.UUID      `json:"client_id"`
	TotalAmount pgtype.Numeric   `json:"total_amount"`
	Status      NullSaleStatus   `json:"status"`
	Created     pgtype.Timestamp `json:"created"`
}

type SaleItem struct {
	ID        int            `json:"id"`
	SaleID    int            `json:"sale_id"`
	ProductID int            `json:"product_id"`
	Quantity  *int           `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
}

type StockMovement struct {
	ID        int              `json:"id"`
	ProductID *int             `json:"product_id"`
	Quantity  *int             `json:"quantity"`
	Action    NullStockAction  `json:"action"`
	Created   pgtype.Timestamp `json:"created"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Data         *string          `json:"data"`
	Email        *string          `json:"email"`
	PhoneNumber  []string         `json:"phone_number"`
	PasswordHash string           `json:"password_hash"`
	Role         NullUserRole     `json:"role"`
	Created      pgtype.Timestamp `json:"created"`
	Updated      pgtype.Timestamp `json:"updated"`
}
