// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConsumptionPurchase = `-- name: AddConsumptionPurchase :exec
UPDATE purchase_orders SET consumption=$1
WHERE id=$2
`

type AddConsumptionPurchaseParams struct {
	Consumption pgtype.Numeric `json:"consumption"`
	ID          int            `json:"id"`
}

func (q *Queries) AddConsumptionPurchase(ctx context.Context, arg AddConsumptionPurchaseParams) error {
	_, err := q.db.Exec(ctx, addConsumptionPurchase, arg.Consumption, arg.ID)
	return err
}

const addPurchaseItem = `-- name: AddPurchaseItem :one
INSERT INTO purchase_items (purchase_order_id, product_id, quantity, price, status)
VALUES ($1, $2, $3, $3, $4) RETURNING id
`

type AddPurchaseItemParams struct {
	PurchaseOrderID int  `json:"purchase_order_id"`
	ProductID       int  `json:"product_id"`
	Quantity        int  `json:"quantity"`
	Status          bool `json:"status"`
}

func (q *Queries) AddPurchaseItem(ctx context.Context, arg AddPurchaseItemParams) (int, error) {
	row := q.db.QueryRow(ctx, addPurchaseItem,
		arg.PurchaseOrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Status,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchase_orders (dealer_id)
VALUES ($1) RETURNING id
`

func (q *Queries) CreatePurchase(ctx context.Context, dealerID pgtype.UUID) (int, error) {
	row := q.db.QueryRow(ctx, createPurchase, dealerID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO categories (name, measurement_id)
VALUES ($1, $2) RETURNING id
`

type InsertCategoryParams struct {
	Name          string `json:"name"`
	MeasurementID int    `json:"measurement_id"`
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (int, error) {
	row := q.db.QueryRow(ctx, insertCategory, arg.Name, arg.MeasurementID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (name, category_id)
VALUES ($1, $2) RETURNING id
`

type InsertProductParams struct {
	Name       string `json:"name"`
	CategoryID int    `json:"category_id"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (int, error) {
	row := q.db.QueryRow(ctx, insertProduct, arg.Name, arg.CategoryID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const listMeasurement = `-- name: ListMeasurement :many
SELECT id, name, unit_symbol, created, updated
FROM measurements
`

func (q *Queries) ListMeasurement(ctx context.Context) ([]Measurement, error) {
	rows, err := q.db.Query(ctx, listMeasurement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measurement
	for rows.Next() {
		var i Measurement
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UnitSymbol,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
