// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addExpensesPurchaseItem = `-- name: AddExpensesPurchaseItem :exec
INSERT INTO purchase_expenses (sum, purchase_item_id, data)
VALUES ($1, $2, $3)
`

type AddExpensesPurchaseItemParams struct {
	Sum            pgtype.Numeric `json:"sum"`
	PurchaseItemID int            `json:"purchase_item_id"`
	Data           *string        `json:"data"`
}

func (q *Queries) AddExpensesPurchaseItem(ctx context.Context, arg AddExpensesPurchaseItemParams) error {
	_, err := q.db.Exec(ctx, addExpensesPurchaseItem, arg.Sum, arg.PurchaseItemID, arg.Data)
	return err
}

const addPurchaseItem = `-- name: AddPurchaseItem :one
INSERT INTO purchase_items (purchase_order_id, product_id, quantity, price, status)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type AddPurchaseItemParams struct {
	PurchaseOrderID int            `json:"purchase_order_id"`
	ProductID       int            `json:"product_id"`
	Quantity        int            `json:"quantity"`
	Price           pgtype.Numeric `json:"price"`
	Status          bool           `json:"status"`
}

func (q *Queries) AddPurchaseItem(ctx context.Context, arg AddPurchaseItemParams) (int, error) {
	row := q.db.QueryRow(ctx, addPurchaseItem,
		arg.PurchaseOrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
		arg.Status,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchase_orders (dealer_id)
VALUES ($1) RETURNING id
`

func (q *Queries) CreatePurchase(ctx context.Context, dealerID pgtype.UUID) (int, error) {
	row := q.db.QueryRow(ctx, createPurchase, dealerID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getProductsBalance = `-- name: GetProductsBalance :many
SELECT id, product_id, quantity, sum, updated FROM products_balance
`

func (q *Queries) GetProductsBalance(ctx context.Context) ([]ProductsBalance, error) {
	rows, err := q.db.Query(ctx, getProductsBalance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsBalance
	for rows.Next() {
		var i ProductsBalance
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Quantity,
			&i.Sum,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCategory = `-- name: InsertCategory :one
WITH existing AS (SELECT ctg.id
                  FROM categories as ctg
                  WHERE ctg.name = $1),
     inserted AS (
INSERT
INTO categories ("name", measurement_id, category_id)
SELECT $1,
       $2,
       $3 WHERE NOT EXISTS (SELECT 1 FROM existing)
    RETURNING id
)
SELECT id
FROM inserted
UNION ALL
SELECT id
FROM existing LIMIT 1
`

type InsertCategoryParams struct {
	Name          string `json:"name"`
	MeasurementID int    `json:"measurement_id"`
	CategoryID    *int   `json:"category_id"`
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (int, error) {
	row := q.db.QueryRow(ctx, insertCategory, arg.Name, arg.MeasurementID, arg.CategoryID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const insertProduct = `-- name: InsertProduct :one
WITH existing AS (SELECT p.id, p.category_id
                  FROM products as p
                  WHERE p.name = $1),
     inserted AS (
INSERT
INTO products (name, category_id)
SELECT $1,
       $2 WHERE NOT EXISTS (SELECT 1 FROM existing)
    RETURNING id
)
SELECT id
FROM inserted
UNION ALL
SELECT id
FROM existing LIMIT 1
`

type InsertProductParams struct {
	Name       string `json:"name"`
	CategoryID int    `json:"category_id"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (int, error) {
	row := q.db.QueryRow(ctx, insertProduct, arg.Name, arg.CategoryID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const listMeasurement = `-- name: ListMeasurement :many
SELECT id, name, unit_symbol, created, updated
FROM measurements
`

func (q *Queries) ListMeasurement(ctx context.Context) ([]Measurement, error) {
	rows, err := q.db.Query(ctx, listMeasurement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measurement
	for rows.Next() {
		var i Measurement
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UnitSymbol,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
