// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, phone_number, password_hash, role, data)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type CreateUserParams struct {
	Name         string       `json:"name"`
	Email        *string      `json:"email"`
	PhoneNumber  []string     `json:"phone_number"`
	PasswordHash string       `json:"password_hash"`
	Role         NullUserRole `json:"role"`
	Data         *string      `json:"data"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.Role,
		arg.Data,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
