// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package postgres

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, name, email, phone_number, password_hash, role, data)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, username, name, data, email, phone_number, password_hash, role, created, updated
`

type CreateUserParams struct {
	Username     string       `json:"username"`
	Name         string       `json:"name"`
	Email        *string      `json:"email"`
	PhoneNumber  []string     `json:"phone_number"`
	PasswordHash string       `json:"password_hash"`
	Role         NullUserRole `json:"role"`
	Data         *string      `json:"data"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.Role,
		arg.Data,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Data,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, name, data, email, phone_number, password_hash, role, created, updated
FROM users
where username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Data,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
